name: GitHub-Profile-3D-Contrib

on:
  push:
    branches:
      - main
      
  #schedule: # 03:00 JST == 18:00 UTC
    #- cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.THREEDCONTRIBUTION }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        env:
          TOKEN: ${{ secrets.THREEDCONTRIBUTION }}
          REPO: ${{ github.repository }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "generated" || echo "No changes to commit"

          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${REPO}.git
          git push origin HEAD
